[tool.poetry]
name = "carfuelbackend"
version = "0.1.0"
description = "Carfuel Backend"
authors = ["Sebastian"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
