# Generated by Django 2.2.22 on 2021-05-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthtokenToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'authtoken_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oauth2ProviderAccesstoken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expires', models.DateTimeField()),
                ('scope', models.TextField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'oauth2_provider_accesstoken',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oauth2ProviderApplication',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=100, unique=True)),
                ('redirect_uris', models.TextField()),
                ('client_type', models.CharField(max_length=32)),
                ('authorization_grant_type', models.CharField(max_length=32)),
                ('client_secret', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('skip_authorization', models.BooleanField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('algorithm', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'oauth2_provider_application',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oauth2ProviderGrant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('expires', models.DateTimeField()),
                ('redirect_uri', models.TextField()),
                ('scope', models.TextField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('code_challenge', models.CharField(max_length=128)),
                ('code_challenge_method', models.CharField(max_length=10)),
                ('nonce', models.CharField(max_length=255)),
                ('claims', models.TextField()),
            ],
            options={
                'db_table': 'oauth2_provider_grant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oauth2ProviderIdtoken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jti', models.UUIDField(unique=True)),
                ('expires', models.DateTimeField()),
                ('scope', models.TextField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'oauth2_provider_idtoken',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oauth2ProviderRefreshtoken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('revoked', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oauth2_provider_refreshtoken',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('ordernumber', models.CharField(max_length=50)),
                ('ordertime', models.DateTimeField()),
                ('orderamount', models.FloatField()),
                ('orderlocation', models.CharField(max_length=255)),
                ('deliverytime', models.DateTimeField(blank=True, null=True)),
                ('orderdetails', models.CharField(blank=True, max_length=255, null=True)),
                ('orderstatus', models.CharField(max_length=50)),
                ('deliveryagent', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registeredvehicles',
            fields=[
                ('carid', models.AutoField(primary_key=True, serialize=False)),
                ('carname', models.CharField(max_length=50)),
                ('carmodel', models.CharField(max_length=50)),
                ('carcolor', models.CharField(max_length=50)),
                ('carregnumber', models.CharField(max_length=50)),
                ('registeredon', models.DateTimeField()),
            ],
            options={
                'db_table': 'registeredvehicles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('roleid', models.AutoField(primary_key=True, serialize=False)),
                ('rolename', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_on', models.DateTimeField()),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_admin', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_agent', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
