# Generated by Django 4.2.5 on 2024-01-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CarfuApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name="taskactivity",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
