# Generated by Django 4.2.5 on 2023-12-15 07:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CarfuApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authuser",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="taskactivity",
            options={"managed": True},
        ),
        migrations.AlterModelTable(
            name="authuser",
            table="CarfuApp_authuser",
        ),
        migrations.AlterModelTable(
            name="task",
            table="CarfuApp_task",
        ),
        migrations.AlterModelTable(
            name="taskactivity",
            table="CarfuApp_taskactivity",
        ),
    ]
