# Generated by Django 4.1.7 on 2023-03-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarfuApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='car_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='registeredvehicles',
            old_name='carid',
            new_name='id',
        ),
    ]
