# Generated by Django 4.1.7 on 2023-03-15 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarfuApp', '0002_rename_car_id_cars_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
