# Generated by Django 4.2.5 on 2024-02-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CarfuApp", "0002_alter_task_id_alter_taskactivity_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("completed", "Completed")],
                default="pending",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="taskactivity",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("completed", "Completed")],
                default="pending",
                max_length=50,
            ),
        ),
    ]
