# Generated by Django 2.2.28 on 2022-10-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarfuApp', '0003_auto_20221022_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=1000)),
                ('model', models.CharField(max_length=1000)),
                ('color', models.CharField(max_length=20)),
                ('yom', models.CharField(max_length=4)),
                ('mileage', models.CharField(blank=True, max_length=1000)),
                ('sell_status', models.BooleanField(default=False)),
                ('price', models.CharField(max_length=1000)),
                ('imageUrl', models.ImageField(blank=True, upload_to='car_images/')),
                ('image_data', models.BinaryField(blank=True)),
                ('car_description', models.CharField(blank=True, max_length=1000)),
                ('saved_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'cars',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CarsModel',
        ),
    ]
