# Generated by Django 5.1.3 on 2024-12-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CarfuApp", "0003_alter_task_status_alter_taskactivity_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "M"), ("Female", "F"), ("Other", "O")],
                max_length=20,
                null=True,
            ),
        ),
    ]
